export class EmployeeInfo
   {
      EmpCode : string;
      EmpName : string;
      Gender : number;
      Designation : string;
      Resident : string;
      Department : string;
      Type : string;
      BusinessNature : string;
      BirthDate : date;
      JoiningDate : date;
      OfficeBranch : string;
      Status : string;
      Location : string;
      StatusDate : string;
      EmailID : string;
      Payby : string;
      ProvidentFund : string;
      AccNo : string;
      PFDeductAmt : number;
      Bank : string;
      BankBranch : string;
      IncomeTex : string;
      TaxDeductAmt : number;
      TINNo : string;
      NationalId : string;
      IsCompanyCar : string;
      CompanyID : number;
      id : number;
      SortOrderdep : number;
      SortOrderDeg : number;
      GradeValue : number;
      GradeID : number;
      Project : string;
      PayScaleID : number;
      Division : string;
      DepartmentID : number;
      DesignationID : number;
      GradeName : string;
      BranchID : number;
      ProjectID : number;
      IsBlock : string;
   }
}