export class View_ExecutiveSalarySummary
   {
      EmpCode : string;
      PeriodID : number;
      PeriodName : string;
      CompanyID : number;
      Basic : number;
      DRN : number;
      Mobl : number;
      HRent : number;
      ENT : number;
      CONV : number;
      MED : number;
      GrossPay : number;
      CALLOW : number;
      PALOW : number;
      LFA : number;
      ELC : number;
      SCOM : number;
      ARRE : number;
      AVD : number;
      FB : number;
      PB : number;
      OALOW : number;
      WAS : number;
      EDU : number;
      BEV : number;
      DA : number;
      INS : number;
      TotalAddi : number;
      Amount : number;
      SW : number;
      CO : number;
      SWADV : number;
      EPS : number;
      PFADV : number;
      LWP : number;
      ODECT : number;
      ASLY : number;
      PFO : number;
      ITAX : number;
      HLON : number;
      TotalDeduct : number;
      TaxYearID : number;
   }
}